apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openproject.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategy.type }}
  selector:
    matchLabels:
      app: {{ include "openproject.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "openproject.name" . }}
    spec:
      containers:
        - name: openproject
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
            - name: OPENPROJECT_DATABASE_ADAPTER
              value: "postgresql"
            - name: OPENPROJECT_DATABASE_HOST
              value: "openproject-postgres"
            - name: OPENPROJECT_DATABASE_PORT
              value: "5432"
            - name: OPENPROJECT_DATABASE_NAME
              value: {{ .Values.postgres.database | quote }}
            - name: OPENPROJECT_DATABASE_USERNAME
              value: {{ .Values.postgres.user | quote }}
            - name: OPENPROJECT_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalSecret.existingSecret }}
                  key: POSTGRES_PASSWORD
          envFrom:
            - secretRef:
                name: {{ .Values.externalSecret.existingSecret }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/openproject/assets
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
      restartPolicy: {{ .Values.restartPolicy }}
