apiVersion: v1
kind: Service
metadata:
  name: {{ include "openproject.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "openproject.name" . }}
  ports:
    - port: 80
      targetPort: {{ .Values.containerPort }}
