services:
  argocd:
    enabled: true
    host: argocd.lesicnik.eu
    ip: 192.168.10.90
  longhorn:
    enabled: true
    host: longhorn.lesicnik.eu
    ip: 192.168.10.90
  vault:
    enabled: true
    host: vault.lesicnik.eu
    ip: 192.168.10.90
  prometheus:
    enabled: true
    host: prometheus.lesicnik.eu
    ip: 192.168.10.90
  grafana:
    enabled: true
    host: grafana.lesicnik.eu
    ip: 192.168.10.90
  ddns:
    enabled: true
    host: ddns.lesicnik.eu
    ip: 192.168.10.90
  torrent:
    enabled: true
    host: torrent.lesicnik.eu
    ip: 192.168.10.90
  usenet:
    enabled: true
    host: usenet.lesicnik.eu
    ip: 192.168.10.90
  radarr:
    enabled: true
    host: radarr.lesicnik.eu
    ip: 192.168.10.90
  sonarr:
    enabled: true
    host: sonarr.lesicnik.eu
    ip: 192.168.10.90
  lidarr:
    enabled: true
    host: lidarr.lesicnik.eu
    ip: 192.168.10.90
  prowlarr:
    enabled: true
    host: prowlarr.lesicnik.eu
    ip: 192.168.10.90
  tautulli:
    enabled: true
    host: tautulli.lesicnik.eu
    ip: 192.168.10.90
  wireguard:
    enabled: true
    host: wireguard.lesicnik.eu
    ip: 192.168.10.90
  books:
    enabled: true
    host: books.lesicnik.eu
    ip: 192.168.10.90
  actual:
    enabled: true
    host: actual.lesicnik.eu
    ip: 192.168.10.90
  fuel:
    enabled: true
    host: fuel.lesicnik.eu
    ip: 192.168.10.90
  sso:
    enabled: true
    host: sso.lesicnik.eu
    ip: 192.168.10.90
  nextcloud:
    enabled: true
    host: nextcloud.lesicnik.eu
    ip: 192.168.10.90
  photos:
    enabled: true
    host: photos.lesicnik.eu
    ip: 192.168.10.90
  kiosk:
    enabled: true
    host: kiosk.lesicnik.eu
    ip: 192.168.10.90
  ha:
    enabled: true
    host: ha.lesicnik.eu
    ip: 192.168.10.90
  pve:
    enabled: true
    host: pve.lesicnik.eu
    ip: 192.168.10.90
  ugi:
    enabled: true
    host: ugi.lesicnik.eu
    ip: 192.168.10.90
  track:
    enabled: true
    host: track.lesicnik.eu
    ip: 192.168.10.90
  cloud:
    enabled: true
    host: cloud.lesicnik.eu
    ip: 192.168.10.90

upstream:
  primary: "94.140.14.49"
  secondary: "94.140.14.59"

image:
  repository: coredns/coredns
  tag: "1.14.0"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 53
  loadBalancerIP: "192.168.10.91"

resources:
  requests:
    cpu: 10m
    memory: 40Mi
  limits:
    cpu: 50m
    memory: 64Mi