apiVersion: apps/v1
kind: Deployment
metadata:
  name: lemur-pitwall
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app: lemur-pitwall
  template:
    metadata:
      labels:
        app: lemur-pitwall
    spec:
      containers:
        - name: lemur-pitwall
          image: "{{ if .Values.image.digest }}{{ .Values.image.repository }}@{{ .Values.image.digest }}{{ else }}{{ .Values.image.repository }}:{{ .Values.image.tag }}{{ end }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: web
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          startupProbe:
            tcpSocket:
              port: web
            failureThreshold: 30
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: web
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: web
            initialDelaySeconds: 5
            periodSeconds: 5
