apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "actual-budget.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "actual-budget.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "actual-budget.name" . }}
    spec:
      containers:
        - name: actual-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.existingSecret }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
      restartPolicy: {{ .Values.restartPolicy }}