apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"  # Create before everything else
  labels:
    name: {{ .Release.Namespace }}