apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
spec:
  capacity:
    storage: {{ .Values.pv.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.pvc.storageClassName }}
  csi:
    driver: iscsi.csi.k8s.io
    volumeHandle: {{ .Values.pv.volumeHandle }}
    fsType: {{ .Values.pv.fsType }}
    volumeAttributes:
      targetPortal: "{{ .Values.pv.targetPortal }}"
      iqn: "{{ .Values.pv.iqn }}"
      lun: "{{ .Values.pv.lun }}"
