apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
spec:
  capacity:
    storage: {{ .Values.pv.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: {{ .Values.pv.targetPortal }}:3260
    iqn: {{ .Values.pv.iqn }}
    lun: {{ .Values.pv.lun }}
    fsType: {{ .Values.pv.fsType }}
