apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.data.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.data.size }}
  storageClassName: {{ .Values.volume.data.storageClassName }}
