apiVersion: v1
kind: Service
metadata:
  name: {{ include "actual-budget.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "actual-budget.name" . }}
  ports:
    - port: 80
      targetPort: 3000
