apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prometheus-secret
  namespace: prometheus
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: prometheus-secret
    creationPolicy: Owner
  data:
    - secretKey: homeassistant-token
      remoteRef:
        key: prometheus
        property: homeassistant-token
