{{- if .Values.server.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-server
  namespace: {{ .Release.Namespace }}
  annotations:
{{- range $key, $value := .Values.server.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
spec:
  ingressClassName: {{ .Values.server.ingress.ingressClassName | quote }}
{{- if .Values.server.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.server.ingress.hostname | quote }}
      secretName: {{ .Values.server.ingress.tls.secretName | quote }}
{{- end }}
  rules:
  - host: {{ .Values.server.ingress.hostname | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-server
            port:
              number: 80
{{- end }}