apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 9000
    name: http
  - port: 443
    targetPort: 9443
    name: https
  selector:
    app: authentik-server