apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: authentik-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTHENTIK_SECRET_KEY: "{{ .secret_key }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .postgres_password }}"
        POSTGRES_PASSWORD: "{{ .postgres_root_password }}"
        REDIS_PASSWORD: "{{ .redis_password }}"
  data:
    - secretKey: secret_key
      remoteRef:
        key: secret/authentik
        property: secret_key
    - secretKey: postgres_password
      remoteRef:
        key: secret/authentik
        property: postgres_password
    - secretKey: postgres_root_password
      remoteRef:
        key: secret/authentik
        property: postgres_root_password
    - secretKey: redis_password
      remoteRef:
        key: secret/authentik
        property: redis_password