apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgresql
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgresql
  clusterIP: None