apiVersion: apps/v1
kind: Deployment
metadata:
  name: wg-easy
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app: wg-easy
  template:
    metadata:
      labels:
        app: wg-easy
    spec:
      containers:
        - name: wg-easy
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: web
              containerPort: {{ .Values.service.webPort }}
              protocol: TCP
            - name: vpn
              containerPort: {{ .Values.service.vpnPort }}
              protocol: {{ .Values.service.vpnPortProtocol }}
          env:
            {{- if .Values.externalSecret.enabled }}
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "wg-easy.fullname" . }}-secret
                  key: PASSWORD
            {{- else if .Values.env.PASSWORD }}
            - name: PASSWORD
              value: {{ .Values.env.PASSWORD | quote }}
            {{- end }}
            {{- if .Values.env.INSECURE }}
            - name: INSECURE
              value: {{ .Values.env.INSECURE | quote }}
            {{- end }}
            {{- if .Values.env.PORT }}
            - name: PORT
              value: {{ .Values.env.PORT | quote }}
            {{- end }}
            {{- if .Values.env.HOST }}
            - name: HOST
              value: {{ .Values.env.HOST | quote }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: {{ .Values.pvc.mountPath }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: web
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: web
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
