gateway:
  name: traefik-gateway
  namespace: traefik

services:
  homeassistant:
    enabled: true
    host: ha.lesicnik.eu
    ip: 192.168.10.8
    port: 8123
    scheme: http

internalServices:
  ugi:
    enabled: true
    host: ugi.lesicnik.eu
    ip: 192.168.10.9
    port: 9443
    scheme: https
    insecureSkipVerify: true

  pve:
    enabled: true
    host: pve.lesicnik.eu
    ip: 192.168.10.10
    port: 8006
    scheme: https
    insecureSkipVerify: true

  login:
    enabled: true
    host: login.lesicnik.eu
    ip: 192.168.10.20
    port: 80
    scheme: http

  actual-dev:
    enabled: true
    host: actual-dev.lesicnik.eu
    ip: 192.168.10.20
    port: 80
    scheme: http
