services:
  immich:
    enabled: true
    host: immich.lesicnik.eu
    ip: 192.168.10.21
    port: 2283
  homeassistant:
    enabled: true
    host: ha.lesicnik.eu
    ip: 192.168.10.8
    port: 8123

internalServices:
  beszel:
    enabled: true
    host: beszel.local
    ip: 192.168.10.21
    port: 8090

ingress:
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    enabled: true
    secretName: reverse-proxy-tls