services:
  homeassistant:
    enabled: true
    host: ha.lesicnik.eu
    ip: 192.168.10.8
    port: 8123

internalServices:
  ugi:
    enabled: true
    host: ugi.lesicnik.eu
    ip: 192.168.10.9
    port: 443
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/proxy-ssl-verify: "false"

  pve:
    enabled: true
    host: pve.lesicnik.eu
    ip: 192.168.10.10
    port: 443

ingress:
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    enabled: true
    secretName: reverse-proxy-tls