replicaCount: 1

image:
  repository: hashicorp/http-echo
  tag: "1.0.0"
  pullPolicy: IfNotPresent

args:
  - "-text=hello world"

containerPort: 5678

service:
  type: ClusterIP
  port: 80

gateway:
  name: traefik-gateway
  namespace: traefik

route:
  hostname: hello.local
  path: "/"

resources: {}
