apiVersion: v2
name: cert-manager
description: cert-manager installation for certificate management
type: application
version: 1.0.0

dependencies:
  - name: cert-manager
    version: v1.19.1
    repository: https://charts.jetstack.io