cert-manager:
  installCRDs: true
  
  resources:
    requests:
      cpu: 10m
      memory: 75Mi
    limits:
      cpu: 50m
      memory: 128Mi
  
  webhook:
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 50m
        memory: 75Mi
  
  cainjector:
    resources:
      requests:
        cpu: 10m
        memory: 40Mi
      limits:
        cpu: 50m
        memory: 75Mi
  
  prometheus:
    enabled: true