replicaCount: 1

strategy:
  type: Recreate

image:
  repository: linuxserver/radarr
  tag: "6.0.4"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 7878

ingress:
  enabled: false
  hostname: radarr.lesicnik.eu
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  tls:
    enabled: true
    secretName: radarr-lesicnik-eu-tls

gateway:
  name: traefik-gateway
  namespace: traefik
  httpSectionName: http
  httpsSectionName: https

route:
  enabled: true
  hostname: radarr.lesicnik.eu
  path: /

# PVC for Radarr config
pvc:
  name: radarr-config
  storageClassName: longhorn
  size: 1Gi
  mountPath: /config

# NFS mount for media storage
nfs:
  enabled: true
  server: 192.168.10.9
  path: /volume1/media
  mountPath: /media

env:
  PUID: "1000"
  PGID: "1000"
  TZ: Europe/Ljubljana

resources:
  requests:
    cpu: 10m
    memory: 256Mi
  limits:
    cpu: 100m
    memory: 512Mi

securityContext:
  fsGroup: 1000
