server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: sso.lesicnik.eu
        paths:
          - path: /
            pathType: Prefix

postgresql:
  host: authentik-postgresql
  database: authentik
  user: authentik

redis:
  host: authentik-redis