server:
  ingress:
    enabled: true
    hostname: sso.lesicnik.eu
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
      enabled: true
      secretName: sso-lesicnik-eu-tls

postgresql:
  host: authentik-postgresql
  database: authentik
  user: authentik

redis:
  host: authentik-redis