nextcloud:
  image: nextcloud:latest
  replicas: 1
  domain: nextcloud.lesicnik.eu

  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 2Gi

  persistence:
    storageClass: longhorn
    size: 50Gi
    mountPath: /var/www/html

postgres:
  image: postgres:18
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  persistence:
    size: 10Gi
    storageClass: longhorn
  user: nextcloud
  database: nextcloud

redis:
  image: redis:latest
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

secrets:
  vaultPath: secret/data/nextcloud

containerPort: 80

externalSecret:
  enabled: true
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  remoteRef:
    key: secret/nextcloud
  existingSecret: nextcloud-secrets

ingress:
  enabled: true
  hostname: nextcloud.lesicnik.eu
  ingressClassName: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100g"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    enabled: true
    secretName: nextcloud-lesicnik-eu-tls