apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  Corefile: |
    .:53 {
        errors
        health {
          lameduck 5s
        }
        ready
        
        # Custom hosts
        hosts {
          {{- range $name, $config := .Values.services }}
          {{- if $config.enabled }}
          {{ $config.ip }} {{ $config.host }}
          {{- end }}
          {{- end }}
          
          fallthrough
        }
        
        # Forward everything else to upstream DNS servers
        forward . {{ .Values.upstream.primary }} {{ .Values.upstream.secondary }} {
          max_concurrent 1000
        }
        
        cache 30
        loop
        reload
        loadbalance
    }