apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 53
    protocol: UDP
    name: dns-udp
  - port: {{ .Values.service.port }}
    targetPort: 53
    protocol: TCP
    name: dns-tcp
  selector:
    app: {{ .Chart.Name }}