image:
  repository: qmcgaw/ddns-updater
  tag: v2.9.0

resources:
  requests:
    cpu: 10m
    memory: 16Mi
  limits:
    cpu: 25m
    memory: 32Mi

ingress:
  enabled: false
  host: ddns.lesicnik.eu

gateway:
  name: traefik-gateway
  namespace: traefik
  httpSectionName: http
  httpsSectionName: https

route:
  enabled: true
  hostname: ddns.lesicnik.eu
  path: /

ddns:
  zoneIdentifier: "07492488333c2516382af2a54f294d56"
  domains:
    - actual.lesicnik.eu
    - sso.lesicnik.eu
    - fuel.lesicnik.eu
    - ha.lesicnik.eu
    - nextcloud.lesicnik.eu
    - photos.lesicnik.eu
    - immich.lesicnik.eu
    - vpn.lesicnik.eu
    - beam.lesicnik.eu
    - track.lesicnik.eu
    - cloud.lesicnik.eu

externalSecret:
  enabled: true
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  remoteRef:
    key: secret/ddns
  existingSecret: ddns-updater-secrets
