image:
  repository: qmcgaw/ddns-updater
  tag: latest

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

ingress:
  enabled: true
  host: ddns.local

ddns:
  zoneIdentifier: "07492488333c2516382af2a54f294d56"
  domains:
    - actual.lesicnik.eu
    - sso.lesicnik.eu
    - fuel.lesicnik.eu
    - ha.lesicnik.eu
    - nextcloud.lesicnik.eu
    - photos.lesicnik.eu
    - immich.lesicnik.eu
    - vpn.lesicnik.eu
    - beam.lesicnik.eu

externalSecret:
  enabled: true
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  remoteRef:
    key: secret/ddns
  existingSecret: ddns-updater-secrets