apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ddns-updater.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ddns-updater.labels" . | nindent 4 }}
data:
  config.json.tpl: |
    {
      "settings": [
        {
          "provider": "cloudflare",
          "zone_identifier": "{{ .Values.ddns.zoneIdentifier }}",
          "domain": "{{ index .Values.ddns.domains 0 }}",
          "ttl": 1,
          "proxied": true,
          "token": "CLOUDFLARE_TOKEN_PLACEHOLDER"
        }
        {{- range $index, $domain := .Values.ddns.domains }}
        {{- if ne $index 0 }}
        ,{
          "provider": "cloudflare",
          "zone_identifier": "{{ $.Values.ddns.zoneIdentifier }}",
          "domain": "{{ $domain }}",
          "ttl": 1,
          "proxied": true,
          "token": "CLOUDFLARE_TOKEN_PLACEHOLDER"
        }
        {{- end }}
        {{- end }}
      ]
    }
