{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "ddns-updater.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ddns-updater.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    {{- toYaml .Values.externalSecret.secretStoreRef | nindent 4 }}
  target:
    name: {{ include "ddns-updater.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: api-token
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key }}
        property: cloudflare
{{- end }}

