{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ddns-updater.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ddns-updater.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - secretName: ddns-lesicnik-eu-tls
    hosts:
      - {{ .Values.ingress.host }}
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "ddns-updater.fullname" . }}
            port:
              number: 8000
{{- end }}