replicaCount: 1

strategy:
  type: Recreate

image:
  repository: linuxserver/prowlarr
  tag: "2.3.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9696

ingress:
  enabled: true
  hostname: prowlarr.lesicnik.eu
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  tls:
    enabled: true
    secretName: prowlarr-lesicnik-eu-tls

# PVC for Prowlarr config
pvc:
  name: prowlarr-config
  storageClassName: longhorn
  size: 1Gi
  mountPath: /config

env:
  PUID: "1000"
  PGID: "1000"
  TZ: Europe/Ljubljana

resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 512Gi

securityContext:
  fsGroup: 1000
