apiVersion: v1
kind: Service
metadata:
  name: crowdsec-traefik-bouncer
  namespace: crowdsec
  labels:
    app.kubernetes.io/name: crowdsec
    app.kubernetes.io/component: bouncer
spec:
  type: {{ .Values.service.bouncer.type }}
  ports:
    - name: http
      port: {{ .Values.service.bouncer.port }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: crowdsec
    app.kubernetes.io/component: bouncer
