certificate:
  name: wildcard-lesicnik-eu
  secretName: default-tls-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.lesicnik.eu"
    - "lesicnik.eu"

gatewayClass:
  enabled: true
  name: traefik
  controllerName: traefik.io/gateway-controller

gateway:
  name: traefik-gateway
  className: traefik
  listeners:
    http:
      enabled: true
      port: 80
    https:
      enabled: true
      port: 443
      tls:
        secretName: default-tls-cert

crowdsec:
  middleware:
    enabled: true
    name: crowdsec-bouncer
  mode: stream
  lapi:
    scheme: http
    host: crowdsec-lapi.crowdsec.svc.cluster.local:8080
    path: /
    keyFile: /etc/crowdsec/api-key

externalSecret:
  enabled: true
  name: crowdsec-bouncer-api-key
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  remoteRef:
    key: secret/crowdsec
    property: api_key

traefik:
  providers:
    kubernetesGateway:
      enabled: true
    kubernetesIngress:
      enabled: false
    kubernetesCRD:
      enabled: true

  gateway:
    enabled: false

  service:
    type: LoadBalancer
    loadBalancerIP: "192.168.10.94"

  logs:
    access:
      enabled: true
      filePath: /var/log/traefik/access.log

  ports:
    web:
      port: 80
    websecure:
      port: 443

  persistence:
    enabled: true
    existingClaim: traefik
    path: /var/log/traefik

  additionalArguments:
    - "--entrypoints.web.http.middlewares=crowdsec-bouncer@kubernetescrd"
    - "--entrypoints.websecure.http.middlewares=crowdsec-bouncer@kubernetescrd"

  volumes:
    - name: crowdsec-bouncer-api-key
      type: secret
      mountPath: /etc/crowdsec

  experimental:
    plugins:
      crowdsec-bouncer:
        moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
        version: v1.6.1
