apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: sabnzbd
  ports:
    - name: web
      port: {{ .Values.service.webPort }}
      targetPort: web
      protocol: TCP
