apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actual
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/community-charts/helm-charts/releases/download/actualbudget-1.8.3/actualbudget-1.8.3.tgz
    targetRevision: HEAD
    chart: "" # Empty chart name when using a direct TGZ URL
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: actualbudget
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
