apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actual
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: actualbudget
    targetRevision: 1.8.3
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: actualbudget
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
