replicaCount: 1

image:
  repository: docker.io/actualbudget/actual-server
  tag: latest
  pullPolicy: IfNotPresent

env:
  ACTUAL_OPENID_DISCOVERY_URL: https://sso.lesicnik.eu
  ACTUAL_OPENID_CLIENT_ID: actual
  ACTUAL_OPENID_CLIENT_SECRET: # Will use existing secret
  ACTUAL_OPENID_SERVER_HOSTNAME: https://actual-dev.lesicnik.eu

existingSecret: actual-server-oidc-secret

restartPolicy: Always

pvc:
  name: actual-data
  size: 10Gi
  storageClassName: nfs-client-ssd

ingress:
  enabled: true
  hostname: actual-dev.lesicnik.eu
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  tls:
    enabled: true
    secretName: actual-dev-tls
