replicaCount: 1

image:
  repository: docker.io/actualbudget/actual-server
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 5006
restartPolicy: Always

env:
  ACTUAL_HTTPS: "true"
  ACTUAL_OPENID_DISCOVERY_URL: "https://sso.lesicnik.eu"
  ACTUAL_OPENID_CLIENT_ID: actual
  ACTUAL_OPENID_SERVER_HOSTNAME: "https://actual-dev.lesicnik.eu"

externalSecret:
  enabled: true
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  remoteRef:
    key: secret/actual
  existingSecret: actual-server-oidc-secret

pv:
  name: actual-pv
  size: 10Gi
  volumeHandle: actual-lun0
  fsType: ext4
  targetPortal: 192.168.10.9
  iqn: iqn.2025-03.com.ugreen:target-1.47475697ff
  lun: "0"

pvc:
  name: actual-pvc
  size: 10Gi
  storageClassName: iscsi-csi

ingress:
  enabled: true
  hostname: actual-dev.lesicnik.eu
  ingressClassName: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
  tls:
    enabled: false
    #secretName: actual-dev-tls
