replicaCount: 1
strategy:
  type: Recreate
files:
  server: /data/server-files
  user: /data/user-files
persistence:
  enabled: true
  storageClass: nfs-client-hdd
  size: 10Gi
  existingClaim: ""
login:
  method: openid
  allowedLoginMethods:
    - openid
  openid:
    enforce: true
    providerName: "Authentik"
    discoveryUrl: "https://login.lesicnik.eu/application/o/actual/.well-known/openid-configuration"
    existingSecret:
      name: actual-server-oidc-secret
      clientIdKey: ACTUAL_OPENID_CLIENT_ID
      clientSecretKey: ACTUAL_OPENID_CLIENT_SECRET

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: actual-dev.lesicnik.eu
      paths:
        - path: /
          pathType: Prefix