replicaCount: 1

image:
  repository: docker.io/actualbudget/actual-server
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 5006
restartPolicy: Always

env:
  ACTUAL_HTTPS: "true"
  ACTUAL_OPENID_DISCOVERY_URL: "https://sso.lesicnik.eu"
  ACTUAL_OPENID_CLIENT_ID: actual
  ACTUAL_OPENID_SERVER_HOSTNAME: "https://actual.lesicnik.eu"

externalSecret:
  enabled: true
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  remoteRef:
    key: secret/actual
  existingSecret: actual-server-oidc-secret

pvc:
  name: actual-pvc
  size: 10Gi
  storageClassName: longhorn

ingress:
  enabled: true
  hostname: actual.lesicnik.eu
  ingressClassName: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    enabled: true
    secretName: actual-lesicnik-eu-tls