replicaCount: 1

image:
  repository: docker.io/actualbudget/actual-server
  tag: latest
  pullPolicy: IfNotPresent

env:
  ACTUAL_OPENID_DISCOVERY_URL: https://sso.lesicnik.eu
  ACTUAL_OPENID_CLIENT_ID: actual
  ACTUAL_OPENID_SERVER_HOSTNAME: https://actual-dev.lesicnik.eu

existingSecret: actual-server-oidc-secret
restartPolicy: Always

pvc:
  name: actual-data
  size: 10Gi
  storageClassName: nfs-client-ssd

ingress:
  enabled: true
  hostname: actual-dev.lesicnik.eu
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
  tls:
    enabled: false
    #secretName: actual-dev-tls

externalSecret:
  enabled: true
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  remoteRef:
    key: secret/actual

env:
  ACTUAL_HTTPS: "true"