replicaCount: 0

strategy:
  type: Recreate

image:
  repository: docker.io/actualbudget/actual-server
  tag: 26.3.0
  pullPolicy: IfNotPresent

containerPort: 5006
restartPolicy: Always

resources:
  requests:
    cpu: 10m
    memory: 100Mi
  limits:
    cpu: 100m
    memory: 256Mi

env:
  ACTUAL_HTTPS: "true"
  ACTUAL_OPENID_DISCOVERY_URL: "https://sso.lesicnik.eu"
  ACTUAL_OPENID_CLIENT_ID: actual
  ACTUAL_OPENID_SERVER_HOSTNAME: "https://actual.lesicnik.eu"

externalSecret:
  enabled: true
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  remoteRef:
    key: secret/actual
  existingSecret: actual-server-oidc-secret

pvc:
  name: actual-pvc
  size: 10Gi
  storageClassName: longhorn

gateway:
  name: traefik-gateway
  namespace: traefik
  httpSectionName: http
  httpsSectionName: https

route:
  enabled: true
  hostname: actual-old.lesicnik.eu
  path: /
