replicaCount: 1

strategy:
  type: Recreate

files:
  server: /data/server-files
  user: /data/user-files

persistence:
  enabled: true
  storageClass: nfs-client-hdd
  size: 10Gi
  existingClaim: ""  # leave empty to let Helm create the PVC

login:
  method: "openid"
  openid:
    enforce: true
    providerName: "Authentic"
    tokenExpiration: 3600
    existingSecret:
      name: "actual-server-oidc-secret"
      clientIdKey: "ACTUAL_OPENID_CLIENT_ID"
      clientSecretKey: ""   # not used
      discoveryUrlKey: "ACTUAL_OPENID_DISCOVERY_URL"
      serverHostnameKey: "ACTUAL_OPENID_SERVER_HOSTNAME"
