apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.nextcloud.persistence.size }}
  storageClassName: {{ .Values.nextcloud.persistence.storageClass }}
