replicaCount: 1

strategy:
  type: Recreate

image:
  repository: linuxserver/qbittorrent
  tag: "20.04.1"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  loadBalancerIP: "192.168.10.93"
  webPort: 8080
  torrentPort: 30054
  torrentPortTCP: true
  torrentPortUDP: true

ingress:
  enabled: true
  hostname: torrent.lesicnik.eu
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  tls:
    enabled: true
    secretName: torrent-lesicnik-eu-tls

# PVC for qBittorrent config
pvc:
  name: qbittorrent-config
  storageClassName: longhorn
  size: 1Gi
  mountPath: /config

# NFS mount for media storage
nfs:
  enabled: true
  server: 192.168.10.9
  path: /volume1/media
  mountPath: /media

env:
  PUID: "1000"
  PGID: "1000"
  TZ: Europe/Ljubljana
  WEBUI_PORT: "8080"

resources:
  requests:
    cpu: 50m
    memory: 1024Mi
  limits:
    cpu: 2000m
    memory: 3Gi

securityContext:
  fsGroup: 1000
