{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.existingSecret }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalSecret.existingSecret }}
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key }}
        property: postgres_password
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key }}
        property: postgres_password
{{- end }}
---
{{- if and .Values.kiosk.enabled .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-kiosk-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: immich-kiosk-secret
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key }}
        property: kiosk_api_key
{{- end }}
