replicaCount: 1

strategy:
  type: Recreate

image:
  repository: tautulli/tautulli
  tag: "v2.16.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8181

gateway:
  name: traefik-gateway
  namespace: traefik
  httpSectionName: http
  httpsSectionName: https

route:
  enabled: true
  hostname: tautulli.lesicnik.eu
  path: /

# PVC for Tautulli config
pvc:
  name: tautulli-config
  storageClassName: longhorn
  size: 1Gi
  mountPath: /config

env:
  PUID: "1000"
  PGID: "1000"
  TZ: Europe/Ljubljana

resources:
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 256Mi

securityContext:
  fsGroup: 1000
