replicaCount: 1

strategy:
  type: Recreate

image:
  repository: tautulli/tautulli
  tag: "v2.16.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8181

ingress:
  enabled: true
  hostname: tautulli.lesicnik.eu
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  tls:
    enabled: true
    secretName: tautulli-lesicnik-eu-tls

# PVC for Tautulli config
pvc:
  name: tautulli-config
  storageClassName: longhorn
  size: 1Gi
  mountPath: /config

env:
  PUID: "1000"
  PGID: "1000"
  TZ: Europe/Ljubljana

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

securityContext:
  fsGroup: 1000
