apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actual-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/davidlesicnik/homelab-argo.git
    targetRevision: master
    path: apps/actual-server  # path is relative to repo root
    helm:
      valueFiles:
        - helm-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=false
