# helm-values.yaml

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: actual-dev.lesicnik.eu
      paths:
        - path: /
          pathType: ImplementationSpecific

actualServer:
  config: {}
  extraEnvFrom:
    - secretRef:
        name: actual-server-oidc-secret
  resources:
    limits:
      memory: 256Mi
      cpu: 250m
    requests:
      memory: 128Mi
      cpu: 100m

persistence:
  data:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClassName: nfs-client-hdd

replicaCount: 1
