{{- range $name, $config := .Values.services }}
{{- if $config.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}-external
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $name }}
    chart: {{ $.Chart.Name }}
  {{- with $.Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ $.Values.ingress.className }}
  {{- if $.Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ $config.host }}
    secretName: {{ $.Values.ingress.tls.secretName }}
  {{- end }}
  rules:
  - host: {{ $config.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $name }}-external
            port:
              number: {{ $config.port }}
{{- end }}
{{- end }}