{{- range $name, $config := .Values.services }}
{{- if and $config.enabled (or $config.insecureSkipVerify $config.serverName) }}
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: {{ $name }}-external-transport
  namespace: {{ $.Release.Namespace }}
spec:
  {{- if $config.insecureSkipVerify }}
  insecureSkipVerify: true
  {{- end }}
  {{- if $config.serverName }}
  serverName: {{ $config.serverName | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- range $name, $config := .Values.internalServices }}
{{- if and $config.enabled (or $config.insecureSkipVerify $config.serverName) }}
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: {{ $name }}-local-transport
  namespace: {{ $.Release.Namespace }}
spec:
  {{- if $config.insecureSkipVerify }}
  insecureSkipVerify: true
  {{- end }}
  {{- if $config.serverName }}
  serverName: {{ $config.serverName | quote }}
  {{- end }}
{{- end }}
{{- end }}
