apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: qbittorrent
  ports:
    - name: web
      port: {{ .Values.service.webPort }}
      targetPort: web
      protocol: TCP
    - name: torrent
      port: {{ .Values.service.torrentPort }}
      targetPort: torrent
      protocol: {{ .Values.service.torrentPortProtocol }}
