apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/davidlesicnik/homelab-argo.git
      revision: master
      directories:
      - path: "apps/*"

  template:
    metadata:
      # Create an application name dynamically from the folder name.
      # {{path.basename}} will be "eso", "grafana", etc.
      name: '{{path.basename}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/davidlesicnik/homelab-argo.git
        targetRevision: master
        path: '{{path}}'
      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true