apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app: tautulli
  template:
    metadata:
      labels:
        app: tautulli
    spec:
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
      containers:
        - name: tautulli
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: web
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: PUID
              value: {{ .Values.env.PUID | quote }}
            - name: PGID
              value: {{ .Values.env.PGID | quote }}
            - name: TZ
              value: {{ .Values.env.TZ | quote }}
          volumeMounts:
            - name: config
              mountPath: {{ .Values.pvc.mountPath }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: web
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: web
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
