apiVersion: v1
kind: Service
metadata:
  name: tautulli
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: tautulli
  ports:
    - name: web
      port: {{ .Values.service.port }}
      targetPort: web
      protocol: TCP
