grafana:
  persistence:
    enabled: true
    storageClassName: longhorn
    size: 5Gi
    accessModes:
      - ReadWriteOnce
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.local
    path: /
    pathType: Prefix
  admin:
    existingSecret: grafana-admin-secret
    userKey: admin-user
    passwordKey: admin-password
  service:
    type: ClusterIP
    port: 80
  grafana.ini:
    server:
      root_url: http://grafana.local
      serve_from_sub_path: false
    auth.generic_oauth:
      enabled: true
      name: Authentik
      client_id: Jm3r0VomUFGablL7a3mZWvjEZj26R9xxATFPnLrE
      client_secret: $__file{/etc/secrets/auth_generic_oauth/client_secret}
      scopes: openid profile email groups
      auth_url: https://sso.lesicnik.eu/application/o/authorize/
      token_url: https://sso.lesicnik.eu/application/o/token/
      api_url: https://sso.lesicnik.eu/application/o/userinfo/
      allow_sign_up: true
      role_attribute_path: contains(groups[*], 'authentik Admins') && 'Admin' || 'Viewer'
    feature_toggles:
      enable: provisioning kubernetesDashboards
  extraSecretMounts:
    - name: auth-generic-oauth-secret-mount
      secretName: grafana-admin-secret
      defaultMode: 0440
      mountPath: /etc/secrets/auth_generic_oauth
      readOnly: true
      subPath: ""
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.prometheus.svc.cluster.local:80
        access: proxy
        isDefault: true
        jsonData:
          timeInterval: 30s
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi