apiVersion: v2
name: prometheus-operator
description: Prometheus Operator for Kubernetes monitoring
type: application
version: 1.0.0
dependencies:
  - name: kube-prometheus-stack
    version: "78.2.1"
    repository: https://prometheus-community.github.io/helm-charts