prometheus:
  server:
    enabled: true

    extraFlags:
      - web.enable-remote-write-receiver #enable remote write for recieving data from alloy

    persistentVolume:
      enabled: true
      storageClass: "longhorn"
      size: 50Gi
      accessModes:
        - ReadWriteOnce

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      hosts:
        - prometheus.lesicnik.eu
      paths:
        - /
      pathType: Prefix
      tls:
        - secretName: prometheus-lesicnik-eu-tls
          hosts:
            - prometheus.lesicnik.eu

    resources:
      requests:
        cpu: 10m
        memory: 400Mi
      limits:
        cpu: 300m
        memory: 1024Mi

    retention: "90d"

    global:
      scrape_interval: 30s
      scrape_timeout: 10s
      evaluation_interval: 30s

    extraSecretMounts:
      - name: hass-token
        secretName: prometheus-secret
        mountPath: /etc/prometheus/secrets
        readOnly: true

  alertmanager:
    enabled: false

  kube-state-metrics:
    enabled: true

  prometheus-node-exporter:
    enabled: false

  prometheus-pushgateway:
    enabled: false

  serverFiles:
    alerting_rules.yml: {}
    recording_rules.yml: {}
    rules: {}
    alerts: {}

    prometheus.yml:
      rule_files:
        - /etc/config/recording_rules.yml
        - /etc/config/alerting_rules.yml
        - /etc/config/rules
        - /etc/config/alerts

      # Custom scrape configs - appended to Helm chart defaults
      scrape_configs:
        - job_name: 'longhorn'
          kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
              - longhorn-system
          relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: longhorn-backend
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: manager
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace

        - job_name: "hass"
          scrape_interval: 60s
          metrics_path: /api/prometheus
          authorization:
            credentials_file: /etc/prometheus/secrets/homeassistant-token
          scheme: https
          static_configs:
            - targets: ['ha.lesicnik.eu']
