kube-prometheus-stack:
  prometheusOperator:
    enabled: true
  
  prometheus:
    enabled: true
    prometheusSpec:
      additionalScrapeConfigs:
        - job_name: 'talos-kubelet'
          kubernetes_sd_configs:
            - role: node
          scheme: https
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      retention: 365d
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: longhorn
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 30Gi
  
  grafana:
    enabled: true
    # Use existing secret for admin password
    admin:
      existingSecret: grafana-admin-secret
      userKey: username
      passwordKey: password
    
    persistence:
      enabled: true
      storageClassName: longhorn
      size: 5Gi
    
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - grafana.local
      path: /
      pathType: Prefix
  
  alertmanager:
    enabled: true
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: longhorn
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
  
kube-prometheus-stack:
  nodeExporter:
    enabled: false 
  
  kubeStateMetrics:
    enabled: true

  crds:
    enabled: false  