youtrack:
  image:
    repository: jetbrains/youtrack
    pullPolicy: IfNotPresent
    tag: 2025.3.119033

  podSecurityContext:
    fsGroup: 13001

  securityContext:
    runAsNonRoot: true
    runAsGroup: 13001
    runAsUser: 13001
    privileged: false
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    capabilities:
      drop:
      - ALL
    seccompProfile:
      type: RuntimeDefault

  resources:
    requests:
      cpu: 300m
      memory: 2000Mi
    limits:
      cpu: 500m
      memory: 2Gi

  persistence:
    data:
      name: youtrack-data
      storageClassName: longhorn
      storageSize: 10Gi
      accessModes:
        - ReadWriteOnce

    logs:
      name: youtrack-logs
      storageClassName: longhorn
      storageSize: 5Gi
      accessModes:
        - ReadWriteOnce

    conf:
      name: youtrack-config
      storageClassName: longhorn
      storageSize: 1Gi
      accessModes:
        - ReadWriteOnce

    backups:
      backupType: volumeStorage
      name: youtrack-backup

      volumeStorage:
        storageClassName: longhorn
        storageSize: 10Gi
        accessModes:
          - ReadWriteOnce

  config:
    name: configmap
    baseUrl: "https://track.lesicnik.eu"
    youtrackDisableCheckForUpdate: true
    statisticsUpload: false
    xmx: 1536m
    metaspaceSize: 350m
    maxMetaspaceSize: 350m

  service:
    enabled: true
    name: http
    port: 8080
    protocol: TCP

  ingress:
    enabled: false

gateway:
  name: traefik-gateway
  namespace: traefik
  httpSectionName: http
  httpsSectionName: https

route:
  enabled: true
  path: "/"
