{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ocis-secrets
  labels:
    app: ocis
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalSecret.existingSecret }}
    creationPolicy: Owner
  data:
    - secretKey: IDM_ADMIN_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key }}
        property: admin_password
    - secretKey: OCIS_JWT_SECRET
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key }}
        property: jwt_secret
    - secretKey: OCIS_TRANSFER_SECRET
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key }}
        property: transfer_secret
    - secretKey: OCIS_MACHINE_AUTH_API_KEY
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key }}
        property: machine_auth_api_key
    {{- if .Values.oidc.enabled }}
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key }}
        property: oidc_client_id
    {{- end }}
{{- end }}
