apiVersion: v1
kind: Service
metadata:
  name: ocis
  labels:
    app: ocis
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ocis
