apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
  namespace: grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana
        property: username
    - secretKey: admin-password
      remoteRef:
        key: grafana
        property: password
    - secretKey: client_secret
      remoteRef:
        key: grafana
        property: auth-secret
    - secretKey: postgres-password
      remoteRef:
        key: grafana
        property: postgres-password