{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/component: crowdsec
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalSecret.name }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        api-key: "{{ `{{ .api_key }}` }}"
  data:
    - secretKey: api_key
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key }}
        property: {{ .Values.externalSecret.remoteRef.property }}
{{- end }}
